import torch
import numpy as np
import torch.nn.functional as F
from classifier import CNN
import json
import os
from torch.utils.data import Dataset, DataLoader

# 配置
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# ⚠️ 指向我们刚用 JSON 训练出来的新影子模型！
SHADOW_MODEL_PATH = 'results/CIFAR10/shadow_json_aligned/best_checkpoint_ep.pth'

# JSON 数据加载器 (确保精度和 Go 完全一致)
class ShadowJSONDataset(Dataset):
    def __init__(self, json_path):
        print(f"[*] 正在加载 JSON 数据集: {json_path} ...")
        with open(json_path, 'r') as f:
            self.data = json.load(f)
            
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        # 恢复成 (3, 32, 32) 的 Tensor，完美保留 Go 的底层浮点精度
        image_tensor = torch.tensor(item['Image'], dtype=torch.float32).view(3, 32, 32)
        label_tensor = torch.tensor(item['Label'], dtype=torch.long)
        return image_tensor, label_tensor

def get_losses(model, loader):
    model.eval()
    losses = []
    print(f"[*] 计算 {len(loader.dataset)} 个样本的 Loss...")
    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(DEVICE), target.to(DEVICE)
            output = model(data)
            # 计算 CrossEntropy Loss 
            loss = F.cross_entropy(output, target, reduction='none')
            losses.extend(loss.cpu().numpy().tolist())
    return np.array(losses)

def main():
    if not os.path.exists(SHADOW_MODEL_PATH):
        print(f"[!] 致命错误: 找不到对齐版的影子模型 -> {SHADOW_MODEL_PATH}")
        print("请先在 main.py 里运行 action=7 来训练它！")
        return

    # 1. 加载影子模型
    print("[*] Loading Aligned Shadow Model...")
    model = CNN('CNN7', 'CIFAR10').to(DEVICE)
    ckpt = torch.load(SHADOW_MODEL_PATH, map_location=DEVICE)
    if 'state_dict' in ckpt: ckpt = ckpt['state_dict']
    
    clean_ckpt = {}
    for k, v in ckpt.items():
        if k.startswith('module.'): clean_ckpt[k[7:]] = v
        else: clean_ckpt[k] = v
    model.load_state_dict(clean_ckpt)

    # 2. 加载影子数据 (JSON 模式)
    print("[*] Loading Datasets from JSON...")
    
    if not os.path.exists('shadow_train_data.json'):
        print("[!] 致命错误: 找不到 shadow_train_data.json")
        return

    # 加载 Member 数据
    train_dataset = ShadowJSONDataset('shadow_train_data.json')
    shadow_train_loader = DataLoader(train_dataset, batch_size=128, shuffle=False)
    member_losses = get_losses(model, shadow_train_loader)

    # 3. 计算统计指标
    print(f"[*] Analyzing distributions...")
    print(f"    [🌟] 成员 (Member) Loss 平均值: {np.mean(member_losses):.6f}")

    # 4. 计算 Tau (阈值) 取成员 Loss 的 95% 分位数
    tau_95 = float(np.percentile(member_losses, 95))
    
    result = {
        "threshold": tau_95, 
        "mean_member_loss": float(np.mean(member_losses)),
        "std_member_loss": float(np.std(member_losses)),
        "description": "Generated by calc_thresholds.py (JSON Aligned Version)"
    }

    # 5. 保存报告
    with open('shadow_config.json', 'w') as f:
        json.dump(result, f, indent=4)
    
    print(f"\n[+] 阈值标定大功告成！已生成报告 shadow_config.json:")
    print(json.dumps(result, indent=4))

if __name__ == '__main__':
    main()