import torch
import numpy as np
import torch.nn.functional as F
from classifier import CNN
from utils import load_dataset
import json
import argparse
import os

# 配置
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'
# 注意：这里我们要加载的是 Shadow 模型，不是 Target
# 确保你已经运行过 action=1 并且有 shadow 模型
SHADOW_MODEL_PATH = 'CIFAR10/shadow/3000/best_checkpoint_ep.pth' 

def get_losses(model, loader):
    model.eval()
    losses = []
    print(f"[*] Calculating loss for {len(loader.dataset)} samples...")
    with torch.no_grad():
        for data, target in loader:
            data, target = data.to(DEVICE), target.to(DEVICE)
            output = model(data)
            # 计算 CrossEntropy Loss (reduction='none' 拿每个样本的 loss)
            loss = F.cross_entropy(output, target, reduction='none')
            losses.extend(loss.cpu().numpy().tolist())
    return np.array(losses)

def main():
    if not os.path.exists(SHADOW_MODEL_PATH):
        print(f"[!] 找不到影子模型: {SHADOW_MODEL_PATH}")
        print("请先运行 main.py (action=1) 训练影子模型！")
        return

    # 1. 加载影子模型
    print("[*] Loading Shadow Model...")
    model = CNN('CNN7', 'CIFAR10').to(DEVICE)
    # 偷懒直接加载 state_dict (假设你是最新的 server.py 标准保存的)
    ckpt = torch.load(SHADOW_MODEL_PATH, map_location=DEVICE)
    if 'state_dict' in ckpt: ckpt = ckpt['state_dict']
    
    clean_ckpt = {}
    for k, v in ckpt.items():
        if k.startswith('module.'): clean_ckpt[k[7:]] = v
        else: clean_ckpt[k] = v
    model.load_state_dict(clean_ckpt)

    # 2. 加载影子数据
    # 使用 mode='shadow' 来获取用来训练 Shadow 的数据 (Members)
    # utils.py 逻辑：mode='shadow' 返回的 train_loader 是 Member
    # 我们还需要 Non-member (shadow 的 test set)
    print("[*] Loading Datasets...")
    args = argparse.Namespace(batch_size=128) # 大 batch 跑得快
    
    # 获取 Shadow 的 Member (即 Shadow 的训练集)
    # 注意：根据 utils.py 逻辑，Train_Shadow_Model 用的是 load_dataset(..., mode='shadow')
    shadow_train_loader = load_dataset(args, 'CIFAR10', cluster=3000, mode='shadow')
    
    # 获取 Shadow 的 Non-Member (我们复用 target 的 test loader 作为通用的 non-member 池)
    # 因为 Shadow 的训练数据是专门切出来的，Test 数据可以是公共的测试集
    _, test_loader = load_dataset(args, 'CIFAR10', cluster=3000, mode='target')

    # 3. 计算 Loss 分布
    member_losses = get_losses(model, shadow_train_loader)
    non_member_losses = get_losses(model, test_loader)

    # 4. 计算统计指标
    print(f"[*] Analyzing distributions...")
    print(f"    Member Loss Mean: {np.mean(member_losses):.4f}")
    print(f"    Non-Mem Loss Mean: {np.mean(non_member_losses):.4f}")

    # 计算 Tau (阈值)
    # 策略 A: 95% TPR (即 95% 的 Member 会被判定为 Member，寻找阈值上限)
    # 即：只有 5% 的 Member Loss 会高于这个值
    # 但是 MIA 通常找的是低 Loss，所以我们找 Percentile 95
    
    # 简单策略：以 Member 的 Loss 分布为准
    # 找出 95% 的 Member 都小于该 Loss 的点
    tau_95 = float(np.percentile(member_losses, 95))
    
    # 平衡点策略 (Optional)：Member 和 Non-Member 的交界处
    # 这里我们只输出 member 的分布特征给 Go
    
    result = {
        "threshold": tau_95, # 阈值
        "mean_member_loss": float(np.mean(member_losses)),
        "std_member_loss": float(np.std(member_losses)),
        "description": "Generated by calc_thresholds.py"
    }

    # 5. 保存
    with open('shadow_config.json', 'w') as f:
        json.dump(result, f, indent=4)
    
    print(f"[+] 配置生成完毕！shadow_config.json: {result}")

if __name__ == '__main__':
    main()